### ISSUE TITLE
System76 Hardware Firmware Updates in Pop

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/gnome-control-center#1]
We currently ship a separate utility to manage firmware updates on System76 hardware. We'd like to pull this functionality into a natural location on Pop!_OS.

* Add **Computer Firmware** to Settings > About
* Condition on System76 Hardware with automated firmware updates
* Add additional computer information to the About screen above Memory.
     * Computer System76 Oryx Pro
     * Model oryp4
* Add additional instructions to the firmware update tool (Loading defaults for instance)

![pop about settings](https://user-images.githubusercontent.com/3430283/51067120-54b26580-15cc-11e9-8f74-049ff4ad8684.png)

![firmware update confirmation](https://user-images.githubusercontent.com/3430283/51067122-567c2900-15cc-11e9-80ea-3be327f1f95f.png)

**Comment by brs17** [comment]
How does one look up their current firmware version if there is no update available? Speaking to support, they often ask for the firmware versions from the current system76-firmware application.

**Comment by brs17** [comment]
Currently the firmware-daemon also has a "Reinstall Firmware" option that is used from time to time in diagnosing customer issues.

**Comment by WatchMkr** [comment]
When no update is available, use the following copy in the firmware box.

"The latest firmware version 1.04.05s is installed" The button action can be "Reinstall".

**Comment by brs17** [comment]
We need to provide more than just the BIOS version as seen in the following screenshot: ![firmware](https://user-images.githubusercontent.com/7460774/55644784-2770f000-5794-11e9-8c3e-4ee7da256447.png)

Obviously we can definitely be smarter and not show EC2 when that is N/A if we wanted.

**Comment by mmstick** [comment]
We could display that info directly underneath the "Computer Firmware" header, and above the frame with the upgrade button.

**Comment by WatchMkr** [comment]
With where we are headed with open firmware, I don't think we plan to provide the ability to enable the ME. Therefore, we can omit ME disabled.

We should have two lines available in the frame. I've seen this on other frames in Gnome Settings such as mouse/touchpad. (take a look at Refresh OS install in the above mockup. The second line in a smaller and copied from styles there). Let's attempt to keep the information together within the frame.

If new firmware is available:
Line 1: "Firmware Update Available"
Line 2: "Installed firmware: BIOS 1.05.13RSA2, EC 1.05.06b, EC2 1.06.06.d" EC2 if applicable
Button: Update

Clicking Update initiates the confirmation dialog with the new firmware version and changelog for that version.

If new firmware is not available:
Line1: Your firmware is up to date.
Line 2: "Installed firmware: BIOS 1.05.13RSA2, EC 1.05.06b, EC2 1.06.06d" EC2 if applicable
Button: Reinstall

Clicking Reinstall initiates the confirmation dialog with the current firmware version changelog for that version.

**Comment by brs17** [comment]
While yes, at some point all of our products may have the M.E. disabled (and at that point the only argument to show it would be as verification for the customer), at this current point in time, all of our products have the ability to have an enabled M.E. so I do not think we should remove that value for the time being.

Other than that ^^, I :+1: the updated mockup.

**Comment by WatchMkr** [comment]
If it fits cleanly, it’s okay for now. If not, leave it out.
