### ISSUE TITLE
Customization in G-C-C Limits Shrinking to a Single Column

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/gnome-control-center#100]
Smallest size in Pop!_OS
![image](https://user-images.githubusercontent.com/3430283/85893592-5f58be80-b7b0-11ea-8586-67f55dcac8fb.png)

Smallest size in Fedora

![image](https://user-images.githubusercontent.com/3430283/85893611-6c75ad80-b7b0-11ea-9f7d-171cb1a3ab7a.png)

**Comment by ids1024** [comment]
It seems this is the result of [0027-window-Stop-using-HdyLeaflet.patch](https://github.com/pop-os/gnome-control-center/blob/master_focal/debian/patches/0027-window-Stop-using-HdyLeaflet.patch), which was added by Ubuntu.

At first glance, it builds and runs fine without that patch, so this is trivial to address; depending on whether or not the concerns the Canonical developer had seem to (still) be relevant.

**Comment by WatchMkr** [comment]
I think we should revert this and ask QA to test. We were using g-c-c with this functionality throughout the dev cycle and didn't see quality issues. @mmstick any objections?

**Comment by ids1024** [comment]
Since it's simple enough, I've opened a PR for this, so it can be tested and merged if everything seems fine.
