### ISSUE TITLE
Settings not opening (Pop_OS 20.1)

### ISSUE THREAD

**Issue by rtheodoro** [pop-os/gnome-control-center#130]
Hi, when I try to open settings it doesn't do anything other than load a few seconds.
I tried opening through the main menu, the sound widget and the command line.
From the command line I got this information:

```
xxxxxx@pop-os:~$ gnome-control-center
gnome-control-center: error while loading shared libraries: libpop_upgrade_gtk.so.0: cannot open shared object file: No such file or directory
xxxxxx@pop-os:~$ sudo apt install gnome-control-center
[sudo] senha para xxxxxx: 
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
gnome-control-center is already the newest version (1:3.38.1-2ubuntu1pop1~1605745629~20.10~4259dd4).
gnome-control-center configurado para instalar manualmente.
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.
```

```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
```
GNOME Shell 3.38.1
```
```
pop-shell:
  Instalado: 1.0.0~1605809546~20.10~1a8b13f
  Candidato: 1.0.0~1605809546~20.10~1a8b13f
  Tabela de versão:
 *** 1.0.0~1605809546~20.10~1a8b13f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```
```
Multi Monitors Add On and Sound Input and Output Device Chooser
```

**Comment by ids1024** [comment]
Strange. I'm not seeing this with the same version of gnome-control-center. What does `apt policy libpop-upgrade-gtk` show?

`libpop-upgrade-gtk` was updated recently (https://github.com/pop-os/upgrade/pull/135) but I don't think that should have had any impact on the shared library path, baring some particularly arcane and bizarre sorcery Debian packaging is doing.

**Comment by rtheodoro** [comment]
> What does `apt policy libpop-upgrade-gtk` show?
```
$ apt policy libpop-upgrade-gtk
libpop-upgrade-gtk:
  Instalado: 0.1.0~1606240865~20.10~351ec93
  Candidato: 0.1.0~1606240865~20.10~351ec93
  Tabela de versão:
 *** 0.1.0~1606240865~20.10~351ec93 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by ids1024** [comment]
I guess it's this: https://www.debian.org/doc/debian-policy/ch-sharedlibs.html#ldconfig

The libraries have ldconfig triggers. Not sure why this issue appeared now.

`sudo ldconfig` should hopefully update the library symlinks and fix it.

**Comment by rtheodoro** [comment]
Thanks a lot! This worked fine!

Another question. My "Tile Window" just disappeared few days ago, with some keyboard shortcuts. 

Do you have any idea why?

**Comment by ids1024** [comment]
What do you mean? Is the tiling menu or the "tile windows" button in it not showing? Or the "tiling" section in keyboard settings?

Some files related to tiling bindings were recently moved from the gnome-control-center package to pop-shell, so the "tiling" section in keyboard settings would have disappear if gnome-control-center were updated without pop-shell being updated. That shouldn't be an issue with the pop-shell version you having installed though.

**Comment by rtheodoro** [comment]
> Is the tiling menu or the "tile windows" button in it not showing? Or the "tiling" section in keyboard settings?

Both. I just can't find it anywhere. It is not on Activities Bar, and also when I try to search in Menu, find nothing.

**Comment by ids1024** [comment]
Hm, `/var/lib/dpkg/info/libpop-upgrade-gtk.triggers` contains:

```
# Triggers added by dh_makeshlibs/13.2.1ubuntu1
activate-noawait ldconfig
```

So I'm pretty sure ldconfig should be run without any manual intervention or changes to the package. Not sure why that isn't (consistently) working...

**Comment by rtheodoro** [comment]
Worked fine!

But the file in my desktop was duplicated. And this "copy" does nothing. Is a small icon.
Saddly, I cant put images here.

**Comment by rtheodoro** [comment]
Worked fine! Tile window is back and also fixed other issues.

But the file in my desktop was duplicated. And this "copy" does nothing. Is a small icon.

Every time I put a new file (or folder) in my desktop, it is duplicated. With a small icon which does nothing.

Sadly, I can't put images here.

EDIT----

I just notice that everything is in English, but my system is in Portuguese (BR).

**Comment by julianschoep** [comment]
Had this same issue. Running `sudo apt-get install libpop-upgrade-gtk` and then `sudo ldconfig` fixed it.

**Comment by rtheodoro** [comment]
![Captura de tela de 2020-12-02 09-46-35](https://user-images.githubusercontent.com/36709613/100874497-6c768980-3483-11eb-80ea-b392a38d5da9.png)

And when I click with the right mouse (in the originals), the options is everything in english. but my system is in Portuguese.

**Comment by jacobgkau** [comment]
> And when I click with the right mouse (in the originals), the options is everything in english. but my system is in Portuguese.

I noticed this with the desktop-icons-ng (ding) extension, mentioned [here](https://github.com/pop-os/desktop-icons-ng/issues/3#issuecomment-735879249). I have opened an issue in the desktop-icons-ng repository about this (it seems to be specific to our packaged version): https://github.com/pop-os/desktop-icons-ng/issues/4 

I don't think the language issue with that extension is related to this GNOME Control Center issue about not opening. As for the duplicate icons, one set is coming from desktop-icons-ng, and I would think the other set is coming from somewhere else. Can you please provide the output of these commands:

```
ls -al ~/.local/share/gnome-shell/extensions
ls -al /usr/share/gnome-shell/extensions
apt policy nemo
```

**Comment by rtheodoro** [comment]
```
$ ls -al ~/.local/share/gnome-shell/extensions
total 16
drwxrwxr-x 4 rtheodoro rtheodoro 4096 nov 11 16:04 .
drwx------ 3 rtheodoro rtheodoro 4096 dez  2 14:13 ..
drwxrwxr-x 5 rtheodoro rtheodoro 4096 nov 11 16:04 multi-monitors-add-on@spin83
drwxrwxr-x 7 rtheodoro rtheodoro 4096 out 31 23:26 sound-output-device-chooser@kgshank.net
```

```
$ ls -al /usr/share/gnome-shell/extensions
total 44
drwxr-xr-x 11 root root 4096 nov  4 09:47 .
drwxr-xr-x  7 root root 4096 nov  4 02:45 ..
drwxr-xr-x  2 root root 4096 out 22 15:08 alt-tab-raise-first-window@system76.com
drwxr-xr-x  2 root root 4096 out 22 15:08 always-show-workspaces@system76.com
drwxr-xr-x  2 root root 4096 out 22 15:08 batteryiconfix@kylecorry31.github.io
drwxr-xr-x  2 root root 4096 out 22 15:08 desktop-icons@csoriano
drwxr-xr-x  2 root root 4096 nov 12 16:55 ding@rastersoft.com
drwxr-xr-x  5 root root 4096 nov 30 22:59 pop-shell@system76.com
drwxr-xr-x  2 root root 4096 out 22 15:08 pop-shop-details@system76.com
drwxr-xr-x  2 root root 4096 out 22 15:08 system76-power@system76.com
drwxr-xr-x  3 root root 4096 out 22 15:08 ubuntu-appindicators@ubuntu.com
```

```
$ apt policy nemo
nemo:
  Instalado: (nenhum)
  Candidato: 4.6.5-1
  Tabela de versão:
     4.6.5-1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
```

**Comment by jacobgkau** [comment]
```
drwxr-xr-x  2 root root 4096 out 22 15:08 desktop-icons@csoriano
drwxr-xr-x  2 root root 4096 nov 12 16:55 ding@rastersoft.com
```

You have two Desktop Icons extensions installed. `ding@rastersoft.com` is the one we are currently providing. Our package for desktop-icons-ng includes an empty transition package for desktop-icons, so this should not happen if you are using the default packages and upgrading normally. I would run the following commands:

```
sudo apt update
sudo apt full-upgrade
```

Then reboot. If you still see the duplicate icons, then run this command: `sudo apt install aptitude`

Then provide the output of these two commands so we can see how you have both extensions installed at the same time:

```
apt policy gnome-shell-extension-desktop-icons
aptitude why gnome-shell-extension-desktop-icons
```

Then run these commands to forcibly remove the old extension:

```
sudo apt autoremove --purge gnome-shell-extension-desktop-icons
sudo rm -rf /usr/share/gnome-shell/extensions/desktop-icons@csoriano`
```

Then reboot again. After that, please keep in mind that this is not a support forum, and this issue was supposed to be about Settings failing to open. There will be updates to `pop-upgrade`, `firmware-manager`, `hidpi-widget`, and `theme-switcher` shortly that are supposed to prevent that from happening.

**Comment by rtheodoro** [comment]
> sudo apt update
> sudo apt full-upgrade

Strange, I got some errors on libreoffice.

```
$ apt policy gnome-shell-extension-desktop-icons
gnome-shell-extension-desktop-icons:
  Instalado: (nenhum)
  Candidato: 0.14.0~1605122430~20.10~fe84f29
  Tabela de versão:
     20.04.0+git20200908-1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu groovy/main i386 Packages
     0.14.0~1605122430~20.10~fe84f29 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages

$ aptitude why gnome-shell-extension-desktop-icons
i   ubuntu-standard         Recomenda plymouth                    
i A plymouth                Sugere    desktop-base                
p   desktop-base            Sugere    gnome | kde-standard | xfce4
                                       | wmaker                   
p   gnome                   Depende   gnome-core (= 1:3.30+3)     
p   gnome-core              Depende   gstreamer1.0-packagekit     
p   gstreamer1.0-packagekit Recomenda gnome-software | apper | pac
                                      kagekit-installer           
p   ubuntu-desktop-minimal  Fornece   packagekit-installer        
p   ubuntu-desktop-minimal  Depende   gnome-shell-extension-deskto
                                      p-icons    
```

>sudo apt autoremove --purge gnome-shell-extension-desktop-icons
> sudo rm -rf /usr/share/gnome-shell/extensions/desktop-icons@csoriano`

The problems with libreoffice appeared here again.

I think I will do a refresh install of Pop. I think is better.

Thanks a lot for your help and attention!

**Comment by fkruczek** [comment]
In case someone still has problems with it - this helped me:

```
sudo apt-get remove gnome-control-center

sudo apt-get remove gnome-control-center-data

sudo apt install gnome-control-center

gnome-control-center
```

**Comment by gp-97** [comment]
Even after following all the mentioned solutions, the problems persists in my case

**Comment by gp-97** [comment]
> Even after following all the mentioned solutions, the problems persists in my case

The problem was solved. Somehow, there existed

*libpop_upgrade_gtk.so.1*

instead of

*libpop_upgrade_gtk.so.0*

in
```
/usr/lib
```

I just renamed **libpop_upgrade_gtk.so.1**  to **libpop_upgrade_gtk.so.0** and Voila!, everything started working as intended

**Comment by mmstick** [comment]
GNOME Settings is being rebuilt. You'll need to undo your change.

**Comment by rafadevx** [comment]
> > Even after following all the mentioned solutions, the problems persists in my case
> 
> The problem was solved. Somehow, there existed
> 
> _libpop_upgrade_gtk.so.1_
> 
> instead of
> 
> _libpop_upgrade_gtk.so.0_
> 
> in
> 
> ```
> /usr/lib
> ```
> 
> I just renamed the it to **libpop_upgrade_gtk.so.0** and Voila!, everything started working as intended

Thanks. I just upgraded to 21.04 and couldn't open the settings. The only solution that worked was renaming the file like you said.

**Comment by MikeyBeez** [comment]
This fixed it for me:  sudo apt install libpop-upgrade-gtk
