### ISSUE TITLE
Gnome control center cannot upgrade, broken packages

### ISSUE THREAD

**Issue by AAnzel** [pop-os/gnome-control-center#133]
After an update, when I do `sudo apt update` it says `1 package can be upgraded. Run 'apt list --upgradable' to see it.`.

When doing `apt list --upgradable` the output is 
``Listing... Done
gnome-control-center/groovy 1:3.38.2-1ubuntu1pop1~1607986537~20.10~4e69115 amd64 [upgradable from: 1:3.38.1-2ubuntu1pop1~1605745629~20.10~4259dd4]
N: There are 2 additional versions. Please use the '-a' switch to see them.``

Then when I do `sudo apt upgrade gnome-control-center` the output is:
``Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:``

``The following packages have unmet dependencies:
 gnome-control-center : Depends: libfirmware-manager (>= 0.1.2) but 0.1.2~1607014663~20.10~0fdfd96 is to be installed
                        Depends: libpop-theme-switcher (>= 0.1.1) but 0.1.1~1607014660~20.10~66b6888 is to be installed
                        Depends: libs76-hidpi-widget (>= 0.1.1) but 0.1.1~1607640801~20.10~6398f4b is to be installed
E: Broken packages
``

**Comment by jawadalkassim** [comment]
same problem

**Comment by brieucdlf** [comment]
Works again thanks :)

**Comment by Rj-Aman** [comment]
After trying very hard i found the below code. This will work for you 100 %. Run it on terminal:
`sudo apt install libpython3.8-minimal=3.8.2-1ubuntu1 libpython3.8-stdlib=3.8.2-1ubuntu1 python3.8-minimal=3.8.2-1ubuntu1 python3.8=3.8.2-1ubuntu1`
`sudo apt install gnome-control-center`
