### ISSUE TITLE
Crash on Displays page when hidpi-daemon isn't installed

### ISSUE THREAD

**Issue by rscircus** [pop-os/gnome-control-center#146]
```
0> gnome-control-center

(gnome-control-center:207311): Gtk-CRITICAL **: 15:33:58.131: gtk_container_add: assertion 'GTK_IS_WIDGET (widget)' failed
[1]    207311 segmentation fault (core dumped)  gnome-control-center
```

These fixes work:

- https://askubuntu.com/questions/1187809/pop-theme-causes-gnome-control-center-segmentation-fault
- https://www.reddit.com/r/pop_os/comments/dmkdo8/gnome_control_center_segmentation_fault_error_pop/

But I don't think this is the right way...

**Comment by rscircus** [comment]
Most likely it's related to the Display pane, as in:

https://www.reddit.com/r/linux4noobs/comments/i1bid5/facing_an_error_in_gnomecontrolcenter_gtkcritical/

**Comment by rscircus** [comment]
My ~~fix~~workaround to this issue is: Install `arandr` and manage displays that way. And ignore the gnome-control-center, as it "pops" when clicking on Display.

**Comment by jacobgkau** [comment]
Just to be clear, are you using Pop!_OS, or are you using the Pop PPA on Ubuntu? (The Ask Ubuntu answer you linked is for the latter, while the Reddit posts are for the former.)

**Comment by jacobgkau** [comment]
Confirmed this crash occurs when `hidpi-daemon` is not installed on Pop; this would be a bug, since that package is a recommends and able to be removed.

**Comment by rscircus** [comment]
Pop 20.10

**Comment by ids1024** [comment]
I guess this has been a problem since https://github.com/pop-os/hidpi-widget/commit/9ff1e814a278b594ac7d0daee5bb22783668af32. It should be simple to update the gnome-control-center patch to handle the `NULL` case.

**Comment by rscircus** [comment]
Thanks for handling it so aptly.
