### ISSUE TITLE
New Appearance options causes uncommonly "tall" interface

### ISSUE THREAD

**Issue by bflanagin** [pop-os/gnome-control-center#158]
![Screenshot from 2021-04-07 08-16-53](https://user-images.githubusercontent.com/10382037/113873152-26f00300-977a-11eb-94fe-f1766454a71f.png)
When not in tiling mode the new appearance dialogs extend passed 1080 pixels.

**Comment by leviport** [comment]
Is this a duplicate of https://github.com/pop-os/desktop-widget/issues/4?

**Comment by bflanagin** [comment]
Sure is
