### ISSUE TITLE
"Open in Software" button does not work

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-control-center#16]
In the "Applications" menu, there is a "Open in Software" button which seems to attempt to open the selected program in the Ubuntu Software Center.

It seems like this button should attempt to open the application in the Pop!_Shop. I would also think the button label should say "Open in Pop!_Shop" instead of "Open in Software"

**Comment by jackpot51** [comment]
Ubuntu Software Center should not exist, and it should say `Show Details`

**Comment by jackpot51** [comment]
Screenie please

**Comment by jackpot51** [comment]
@mmstick this is in this pane:

```
gnome-control-center applications
```
