### ISSUE TITLE
'Search' section of GNOME Settings creates inconsistent UX with Pop! COSMIC

### ISSUE THREAD

**Issue by jroyvde** [pop-os/gnome-control-center#164]
May already be being planned / worked on, if this is the case feel free to close this issue!

Testing out Pop 21.04 in a VM, I've noticed that what would normally be the GNOME 'Activities Overview' search in vanilla GNOME has been repurposed into an applications search, with the new Pop launcher filling the more comprehensive role previously filled by GNOME's overview search.

However, the 'Search' section in GNOME Settings still refers to an 'Activities Overview' which no longer exists in Pop 21.04 with the COSMIC desktop enabled. This could present a UX problem and result in new users becoming confused (they may even think the 'Search' section of the settings refers to the Pop Launcher, especially since they share a similar 'magnifying glass' icon).

Since the new Launcher fills the role of most of the search providers which are now disabled by default, it might make sense to remove this section of the Settings altogether (though this might be frustrating for users who choose to disable COSMIC and pursue a more traditional GNOME UX). A good minimal solution might be to simply alter the 'Search' and 'Activities Overview' texts to read 'Applications Search' or something similar instead.

![image](https://user-images.githubusercontent.com/54386705/117563018-6184ec80-b0e6-11eb-80cc-27010049b363.png)

**Comment by DuttaAB-dev** [comment]
Another option would be to re purpose the search settings and attach them with the pop os launcher, along with adding the ability to search for files, settings and other relevant results in the launcher, as gnome search is really powerful and a major part of almost all gnome user's workflows. And as of now, the pop os launcher is just a distant dream compared to what the gnome shell search provides.

**Comment by jroyvde** [comment]
This issue has been resolved now as the Search section has been removed from the Settings app in 21.04.

#188 raises the new UX problem for Pop!_OS users who disable COSMIC.

**Comment by pabrams** [comment]
There was nothing wrong with the UX. Why must you mess with it.
