### ISSUE TITLE
Remove the Search panel from GCC

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/gnome-control-center#165]
The Search panel shows sources for the Activities overview which isn't relevant to COSMIC

**Comment by isantop** [comment]
Perhaps a copy change would be more appropriate? The search feature from the GNOME Activities overview is still present within COSMIC (via the applications panel)

**Comment by jacobgkau** [comment]
Related: https://github.com/pop-os/gnome-control-center/issues/164

**Comment by WatchMkr** [comment]
I believe search in Applications has been limited to only what would be relevant when searching Applications. Some settings are there which should probably be removed. But universal search in Applications wouldn't make sense. Better to remove the panel. We could perhaps repurpose it for the Launcher at some point.
