### ISSUE TITLE
Camera and microphone disable switch does not work

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-control-center#17]
In the Privacy tab, there are two toggles to disable the Camera and the microphone(independently). 

Upon disabling the camera toggle, the camera still work in Cheese.

Upon disabling the microphone, I went over to the sound tab and saw the microphone still recording.

**Comment by mmstick** [comment]
:grimacing:

**Comment by jackpot51** [comment]
How can you have a disco without sound and video?
