### ISSUE TITLE
Make panels under "Desktop" directly searchable

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/gnome-control-center#174]
This enables users to type "Dock" in the launcher and get the correct result. The Privacy panel has this setup for its sub-panels.

**Comment by jacobgkau** [comment]
Related (or duplicate, but not sure if I opened this in the correct repository): https://github.com/pop-os/desktop-widget/issues/13

**Comment by ids1024** [comment]
> not sure if I opened this in the correct repository

Getting this to work would likely require changes to both repositories, so I guess either fits.

This isn't entirely straightforward to do, given how the panel is currently implemented. "Privacy" is actually multiple different panels, that `gnome-control-center/shell/cc-panel-list.*` has hardcoded to display grouped together. The "Dock" is instead a single panel that defines a custom sidebar widget (like the Applications panel).

It might be possible to get this working, but handling multiple levels of organization like this in gnome-control-center is kind of a mess.

**Comment by ids1024** [comment]
Resolved in https://github.com/pop-os/gnome-control-center/pull/210.
