### ISSUE TITLE
Settings not opening (Pop_OS 21.04)

### ISSUE THREAD

**Issue by albert-de-montserrat** [pop-os/gnome-control-center#182]
Hi, when I try to open settings it loads for a few seconds and does nothing. Trying to open it in the command line I get the following

`xx@pop-os:~$ gnome-control-center 
`
`
gnome-control-center: error while loading shared libraries: libpop_upgrade_gtk.so.0: cannot open shared object file: No such file or directory`

`xx@pop-os:~$sudo apt install libpop-upgrade-gtk`
`
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libpop-upgrade-gtk is already the newest version (1.0.0~1625001113~21.04~88b5fca).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded
`

`NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os`

`xx@pop-os:~$gnome-shell --version`
`** (process:6057): WARNING **: 18:22:54.574: Failed to set RT scheduler: Operation not permitted
GNOME Shell 3.38.4
`

**Comment by Kilgourian** [comment]
I'm seeing this issue too after uninstalling and reinstalling gnome-control-center.  Through APT have tried to reinstall "pop-desktop", libpop-upgrade-gtk and have run the command sudo ldconfig.  None has resolved the issue and seeing the exact same message as what albert-de-montserrat has reported.

thanks

**Comment by mmstick** [comment]
This is a required dependency of gnome-control-center's package in Pop. So it shouldn't be possible to be in a situation where the dependency is missing. Have you verified that the files from the dependency are actually there?

**Comment by Kilgourian** [comment]
mmstick, 
you are correct it is a dependency, and it's not possible but something isn't right with package install.  With your suggestion I double checked the file and interesting enough there is a  symlink in the /usr/lib that is incorrect or is correct, and another is just missing.  What I found is the symlink "libpop_upgrade_gtk.so.1" is pointed to "libpop_upgrade_gtk.so", and is not what I was expecting.

I created a new symlink with the following which resolved the issue: 
`sudo ln -s /usr/lib/libpop_upgrade_gtk.so /usr/lib/libpop_upgrade_gtk.so.0 `

I'm not sure why there was a .1 when there should have been a .0 for the original symlink?  I also didn't remove the .1 in fear of something else using the .1 symlink.

Thanks

**Comment by albert-de-montserrat** [comment]
> mmstick,
> you are correct it is a dependency, and it's not possible but something isn't right with package install. With your suggestion I double checked the file and interesting enough there is a symlink in the /usr/lib that is incorrect or is correct, and another is just missing. What I found is the symlink "libpop_upgrade_gtk.so.1" is pointed to "libpop_upgrade_gtk.so", and is not what I was expecting.
> 
> I created a new symlink with the following which resolved the issue:
> `sudo ln -s /usr/lib/libpop_upgrade_gtk.so /usr/lib/libpop_upgrade_gtk.so.0 `
> 
> I'm not sure why there was a .1 when there should have been a .0 for the original symlink? I also didn't remove the .1 in fear of something else using the .1 symlink.
> 
> Thanks

This fixed it to me as well.

 Thanks a lot
