### ISSUE TITLE
Missing pop-upgrade and libpop-upgrade-gtk dependency on 20.04 LTS?

### ISSUE THREAD

**Issue by boenshao** [pop-os/gnome-control-center#183]
![Screenshot from 2021-07-03 01-40-05](https://user-images.githubusercontent.com/65853605/124311002-9cb01300-db9f-11eb-9445-81453387be9b.png)

![Screenshot from 2021-07-03 01-38-10](https://user-images.githubusercontent.com/65853605/124310917-7be7bd80-db9f-11eb-96f4-a54dff22f03e.png)

So basically after my daily dose of
`sudo apt update && sudo apt upgrade`
and 
`sudo autoremove --purge`
The settings app stop working... restore the auto-removed packages fix the issue.
I guess the new package was miss configured?

**Comment by Rallyflowbro** [comment]
Hey boenshao I'm having the same issue. How were you able to restore the auto-removed packages?

**Comment by boenshao** [comment]
> Hey boenshao I'm having the same issue. How were you able to restore the auto-removed packages?

The removed packages are still in the repository, manually reinstall them should do the trick.
`sudo apt install pop-upgrade  libpop-upgrade-gtk`
The gnome control center should now operate correctly.

I do find that after reinstall the missing packages, the systemd timer of pop-upgrade was not restored (the service was though), so I refresh my system to get it back. You can checkout whether yours are missing by...

```
❯ systemctl list-units | grep upgrade
  pop-upgrade.service                          loaded active running   Pop Upgrade Daemon
  apt-daily-upgrade.timer                      loaded active waiting   Daily apt upgrade and clean activities
❯ cat /lib/systemd/system/apt-daily-upgrade.timer
[Unit]
Description=Daily apt upgrade and clean activities
After=apt-daily.timer

[Timer]
OnCalendar=*-*-* 6:00
RandomizedDelaySec=60m
Persistent=true

[Install]
WantedBy=timers.target
```

If its missing just add it back with systemctl.

**Comment by boenshao** [comment]
> Hey boenshao I'm having the same issue. How were you able to restore the auto-removed packages?

The removed packages are still in the repository, manually reinstall them should do the trick.
`sudo apt install pop-upgrade  libpop-upgrade-gtk`
The gnome control center should now operate correctly.

**Comment by Rallyflowbro** [comment]
> > Hey boenshao I'm having the same issue. How were you able to restore the auto-removed packages?
> 
> The removed packages are still in the repository, manually reinstall them should do the trick.
> `sudo apt install pop-upgrade libpop-upgrade-gtk`
> The gnome control center should now operate correctly.

That worked heckin yes. Thank you.

**Comment by boenshao** [comment]
Latest update fixed the issue.
