### ISSUE TITLE
Decide what to do with Power Profiles in Gnome Settings

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/gnome-control-center#192]
It's nice having them here as well as in the user menu but the settings should correspond with system76-power settings.

![image](https://user-images.githubusercontent.com/3430283/133842865-a12618b6-be00-4d4e-8754-7270ab757e73.png)

**Comment by ids1024** [comment]
It shouldn't be too hard to patch Gnome Control Center to replace that section with one that sets the profiles provided by system76-power.

But for context, this upstream setting uses the new [power-profiles-daemon](https://gitlab.freedesktop.org/hadess/power-profiles-daemon) (the README there includes a brief comparison to other projects, including system76-power).

This sets an ACPI power profile through the [Linux kernel API](https://www.kernel.org/doc/html/latest/userspace-api/sysfs-platform_profile.html), and it looks like it changes some kernel settings as well. Our driver doesn't seem to expose profiles this way (I guess some of the logic we have in system76-power is instead handled by firmware on other hardware?).

**Comment by mmstick** [comment]
We currently set our power profiles by sysfs kernel parameters recommended by powertop. But we could easily start using the newer sysfs API too.

**Comment by mmstick** [comment]
> It could without a doubt have been used as a base for power-profiles-daemon if it was more of an upstream project instead of a PopOS!/System76 project.

What does this even mean?

**Comment by jackpot51** [comment]
If `power-profiles-daemon` is removed, that pane does not show up. It is a recommends by gnome-control-center. I recommend we just remove that from the recommends

**Comment by jackpot51** [comment]
And also have system76-power conflict with it

**Comment by jackpot51** [comment]
Removed in https://github.com/pop-os/gnome-control-center/commit/278fa1f8389fdc6f029c2a77802d9a24aa494853. We can choose to implement something similar with system76-power. I don't see value in power-profiles-daemon.

**Comment by cansozbir** [comment]
I wonder the performance difference between power-profiles-daemon and system76-power on non-system76 laptops and system76 laptops. Did you make an experiment on this topic after gnome releases this feature? If so, sharing it with the users would be perfect.

**Comment by mmstick** [comment]
There's no difference in behavior between system76 and non-system76 systems with system76-power, besides the fan daemon that actively applies an ideal fan curve for specific Thelio desktops.

**Comment by cansozbir** [comment]
Thanks for the answer @mmstick. I was thinking all the system76 laptops has this fan daemon, so it could make more sense to at least try what gnome did, but in this situation, I am continuing with system76 developers' choice :)

**Comment by jackpot51** [comment]
We will ensure anything done in power-profiles-daemon exists in system76-power.

**Comment by mmstick** [comment]
This will support interacting with the Linux ACPI Platform Profile kernel sysfs parameters on hardware that supports it:

https://github.com/pop-os/system76-power/pull/278/files

But from what I can see, this feature is currently only available to certain Lenovo laptops at the moment, as mentioned [here](https://www.phoronix.com/scan.php?page=news_item&px=Lenovo-Platform-Profile-For-512).

**Comment by jackpot51** [comment]
Moved to New Features, since replacing power-profiles-daemon made this view go away. We can consider adding it again but using system76-power
