### ISSUE TITLE
21.10: Workspace changing shortcuts are set up for horizontal workspaces

### ISSUE THREAD

**Issue by leviport** [pop-os/gnome-control-center#193]
In keyboard shortcuts, the hotkey settings for changing workspaces say "left" and "right" instead of "up" and "down". They also default to Disabled, even though `Super` + `Ctrl` + `Up`/`Down ` are set as defaults (presumably by https://github.com/pop-os/gnome-shell-extension-vertical-overview). 

![2021-09-22_14-47](https://user-images.githubusercontent.com/13512097/134419522-0ba75c3e-24a7-4438-988e-20e2ac1415e7.png)

**Comment by alexcarman** [comment]
Does this mean we aren't getting horizontal workspaces for 21.10?

**Comment by jackpot51** [comment]
@alexcarman Correct, Pop 21.10 will retain vertical workspaces. If you want horizontal, disable the vertical overview extension.

**Comment by alexcarman** [comment]
@jackpot51 Thanks! I had emailed your UX team about horizontal workspaces as I'm actually one of the few who likes this change. I know it is probably outside the scope of the work to be done for 21.10, but could this be a user configurable option under the desktop settings? That way you guys could correctly handle the labeling and/or changing of keyboard shortcuts?

**Comment by jackpot51** [comment]
We are intending for it to eventually be a configuration setting

**Comment by jackpot51** [comment]
Fixed in https://github.com/pop-os/mutter/commit/01e827fe92163949a2324ecad0ec4c578c4cb2b0
