### ISSUE TITLE
Super Key Action & Top Bar sections missing when building from source

### ISSUE THREAD

**Issue by yochananmarqos** [pop-os/gnome-control-center#197]
What adds the Super Key Action & Top Bar sections into the Desktop panel? It's there in Pop!_OS 21.10, but when I build everything from source on Manjaro, it's missing. I have all The COSMIC packages installed built from the latest master_impish branches.

Pop_OS!:
![Screenshot from 2021-10-15 12-04-31_crop](https://user-images.githubusercontent.com/5437803/137537331-f3b70369-cb0e-4661-bee6-18ee44e46a0b.png)

Manjaro
![Screenshot from 2021-10-15 12-30-18](https://user-images.githubusercontent.com/5437803/137537280-eebb8958-3443-414a-8a57-840265480472.png)
:

**Comment by mmstick** [comment]
Don't forget to apply the quilt patches https://github.com/pop-os/gnome-control-center/blob/master_impish/debian/patches/series

**Comment by yochananmarqos** [comment]
I'm only using these patches so far:

```
debian/patches/pop/0001-mouse-Add-Disable-While-Typing-toggle-for-touchpad.patch
debian/patches/pop/0001-shell-Fix-bug-when-multiple-panels-use-custom-sideba.patch
debian/patches/pop/pop-mouse-accel.patch
debian/patches/pop/system76-firmware.patch
debian/patches/pop/pop-desktop-widget.patch
debian/patches/pop/0001-keyboard-Pop-_OS-changes-with-support-for-multiple-b.patch
```

Which patch(es) would affect the Desktop panel that I'm not using? Upstream / Debian patches do not need to be applied on Manjaro. Patches for issues that no longer exist or are non-reproducible are also not needed.

**Comment by yochananmarqos** [comment]
@ahoneybun: Poke. Any ideas? Manjaro users are anxious. I'm planning on packaging a COSMIC experience for Manjaro GNOME and perhaps the AUR.

**Comment by ids1024** [comment]
`desktop-widget` checks for the existence of the `org.gnome.shell.extensions.pop-cosmic` gsettings schema. For that to work, it needs to be installed to `/usr/share/glib-2.0/schemas` as in the `.deb` package, rather than in the extension specific location.

**Comment by yochananmarqos** [comment]
@ids1024 Oh, duh. I normally symlink the schema XML from the extensions folder to the glib folder when packaging extensions. I completely missed that. That worked, thanks!
