### ISSUE TITLE
Desktop section navigates straight to General after accessing any sub-page in narrow view

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/gnome-control-center#203]
After navigating into any of the Desktop sub-pages and then back to the topmost page list, accessing the Desktop section again goes straight to the General page instead of the Desktop list:
![desktop-page-selection](https://user-images.githubusercontent.com/7199422/142909011-26a4111d-82d9-4f51-a551-90ed40469add.gif)

This does not happen with the Privacy section:
![privacy-page-selection](https://user-images.githubusercontent.com/7199422/142909025-61a6557c-a6ae-4091-8af3-751519e1ac3b.gif)

This issue was discovered while testing https://github.com/pop-os/gnome-control-center/pull/202.

**Comment by jackpot51** [comment]
Fixed
