### ISSUE TITLE
v22.04: Automatic time zone setting always picks Mountain time

### ISSUE THREAD

**Issue by wagnerck** [pop-os/gnome-control-center#221]
On three different systems (admittedly all on the same local network), upgrading to v22.04 has broken the automatic time zone setting. I'm in Austin, which is Central time, but the automatic setting always sets it to Mountain time instead. This has occurred in a VM, on a spare junker laptop, and on my work system (an _oryp6_).

![Screenshot from 2022-04-13 19-52-40](https://user-images.githubusercontent.com/96320715/163408206-fa70edec-2363-468a-bcdf-f2200b1db99a.png)
![Screenshot from 2022-04-13 18-53-16](https://user-images.githubusercontent.com/96320715/163408214-840e215f-2f23-442b-a28e-7f0730ad8e8e.png)

After upgrading my work laptop to the v22.04 beta, a GNOME notification appeared telling me that it had updated the time zone to MDT:

![Screenshot from 2022-04-13 19-19-39](https://user-images.githubusercontent.com/96320715/163408261-a3bcfd38-3d12-4740-ac99-219d92b2fc9e.png)

Location settings are enabled in the Privacy panel of the Settings app. My understanding is that Pop!OS inherited the geolocation services system from Ubuntu, and that Ubuntu uses `geoclue` for that, so I'm assuming that's what is being used to determine the time zone. Running `systemctl status geoclue.service` shows that the service is running, but it shows an error: `gclue_locator_set_time_threshold: assertion 'GCLUE_IS_LOCATOR (locator)' failed`. It's unclear if this is actually a problem or one of those somewhat meanignless warnings.

The `geoclue-2-demo` package includes a test app at `/usr/libexec/geoclue-2.0/demos/where-am-i`, which _does_ generate a lat+long location that's vaguely in the Austin area, so if the automatic time zone function is using `geoclue` then it _should_ be choosing Central time instead of Mountain for me.

I'm not seeing any kind of geolocation activity in the system logs (`/var/log/syslog` or the output from `journalctl`) and there's nothing useful in the output when I run `gnome-control-center -v timedate` either. I'm completely stumped here, but it definitely started happening when I upgraded these systems to v22.04.

**Comment by XV-02** [comment]
With @linuxgnuru doing the heavy lifting, both this and other anomalous behaviour was witnessed. 
The automatic date and time setting either defaulted to the current Denver timezone standard, or to whatever timezone was manually set - even if set separately from the notional hardware location.

**Comment by cwsystem76** [comment]
Customer with the problem after the upgrade: https://system76.zendesk.com/agent/tickets/66035

**Comment by 13r0ck** [comment]
@cwsystem76 please don't post zendesk links in public channels. Neither do they help engineering solve the issue in any channel, because we don't have access to zendesk.

**Comment by wagnerck** [comment]
Whoops. I got this repo mixed up with one of the private ones. Sorry about that, I'll be more careful moving forward.

**Comment by 13r0ck** [comment]
I am unable to reproduce this. With location services on and using the mullvad VPN, changing my location with the VPN adjusts the timezone successfully

**Comment by wagnerck** [comment]
I can still reproduce on my system. I've recorded a video, although it didn't capture the mouse pointer.

[Edit] Re-did the video because it was a mess. The preview in GitHub doesn't work properly, though.

https://user-images.githubusercontent.com/96320715/166068723-a7c23470-125e-4668-aeb6-07c77f86cb76.mp4

**Comment by 13r0ck** [comment]
Can you try `systemctl disable systemd-timedated.service` and rebooting. Does it work then?

**Comment by wagnerck** [comment]
Disabling `systemd-timedated.service` and rebooting has no affect on the Automatic Time Zone issue. It happens the same as in the previous video, only with the Automatic Date & Time switch turned off. Turning the service off with the switch instead of `systemctl` doesn't make any difference either. This was on a freshly-installed V22.04 system with all updates.

This time I've dived a little deeper, and here's what happens per `syslog` when I enable Automatic Time Zone. I forced a log rotation first to make sure I was looking at just the most recent stuff.

First, these lines:
```
Apr 30 09:42:06 pop-os gsd-datetime[2273]: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
Apr 30 09:42:06 pop-os gsd-datetime[2273]: message repeated 1618 times: [ g_object_ref: assertion 'G_IS_OBJECT (object)' failed]
```
Then these three lines repeat about 1500 times:
```
Apr 30 09:42:06 pop-os gsd-datetime[2273]: gweather_location_has_coords: assertion 'loc != NULL' failed
Apr 30 09:42:06 pop-os gsd-datetime[2273]: gweather_location_get_city_name: assertion 'loc != NULL' failed
Apr 30 09:42:06 pop-os gsd-datetime[2273]: gweather_location_get_country: assertion 'loc != NULL' failed
```
and then finally:
```
Apr 30 09:42:07 pop-os gsd-datetime[2273]: message repeated 1618 times: [ gweather_location_unref: assertion 'loc != NULL' failed]
Apr 30 09:42:07 pop-os systemd-timedated[3955]: Changed time zone to 'America/Denver' (MDT).
```
I've also attached the complete `syslog` in a ZIP file, if it's needed.

[time_zone_syslog.zip](https://github.com/pop-os/gnome-control-center/files/8597117/time_zone_syslog.zip)

**Comment by wagnerck** [comment]
The updates to my system this morning seem to have fixed the time zone issue for me, at least.

![image](https://user-images.githubusercontent.com/96320715/166961523-0035dac1-8f69-473b-9512-e12c10dee9f4.png)

**Comment by 13r0ck** [comment]
Closed via https://github.com/pop-os/gnome-settings-daemon/pull/14#issuecomment-1118723581
