### ISSUE TITLE
Create interface for incompatible repos (in preparation for upgrade)

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-control-center#29]
Listen for repo incompatibility signals, parse their messages, and display a dialog to allow the user to send a response to the daemon to disable these repositories.

**Comment by brs17** [comment]
This is what the notification currently looks like when an incompatible repo is found:

![badrepos](https://user-images.githubusercontent.com/7460774/57031015-b5a98c00-6c03-11e9-94c6-9689e707403b.png)

**Comment by brs17** [comment]
@mmstick testing upgrade from 18.04->19.04 via gnome-control-center, I am prompted twice(for the same repository) with the "Unsupported repository" pop-up. I was not selecting the checkbox. 

Logs:
[journal.log](https://github.com/pop-os/gnome-control-center/files/3135322/journal.log)

**Comment by mmstick** [comment]
I wonder if I should set the icon as the debian package mime icon.

**Comment by brs17** [comment]
@mmstick that might make more sense, but I'm not sure. Also, is there any reason to have a `Cancel` button?

**Comment by mmstick** [comment]
They may want to wait to upgrade until their external repositories are supported.

**Comment by brs17** [comment]
That's a good point.
