### ISSUE TITLE
gnome-control-center crashes if hidpi-daemon is uninstalled

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-control-center#37]
gnome-control-center crashes if the hidpi-daemon is purged from the system.
Error message: `Settings schema 'com.system76.hidpi' is not installed`

**Comment by brs17** [comment]
Possible Solutions:
1. Check for hidpi-daemon before attempting to show integration settings.
2. Make the hidpi-daemon a dependency of gnome-control-center.

I think I much prefer the first option.

**Comment by jackpot51** [comment]
Is this on 18.04 or 19.04?

**Comment by jackpot51** [comment]
It should already be checked, at least on 19.04:
```
  self->settings_hidpi = g_settings_new ("com.system76.hidpi");
  if (self->settings_hidpi) {
```

**Comment by mmstick** [comment]
I remember being told by a GNOME developer at one point that GSettings will crash the program if you supply a path that does not exist. They consider it a programmer error rather than allowing you to handle it. Seems it does indeed crash on 19.04.

**Comment by mmstick** [comment]
[Found this mailing list discussion on the subject from 2011](https://mail.gnome.org/archives/gtk-devel-list/2011-May/msg00111.html), but their rationale is that `g_settings_new ()` should abort instead of returning `NULL` because they consider it to be an installation error if a schema is missing.
