### ISSUE TITLE
19.10: Missing firmware-manager integration

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-control-center#46]
In Pop!_OS 19.10, gnome-control-center is missing firmware-manager integration.

**Comment by jackpot51** [comment]
All the customizations we do to gnome-control-center need to be ported to 19.10

**Comment by mmstick** [comment]
Everything but HiDPI and Appearances patches should be in 19.10 as of the end of yesterday.

**Comment by brs17** [comment]
> Everything but HiDPI and Appearances patches should be in 19.10 as of the end of yesterday.

Created issues: https://github.com/pop-os/gnome-control-center/issues/49 and https://github.com/pop-os/gnome-control-center/issues/48 to reference the patches that are still needed.
