### ISSUE TITLE
Appearance search result description text is cut off

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-control-center#54]
In 19.10, when searching for the Appearance tab in the `Activities` search, the description is cut off. All that is visible is: `Change your background image to a wallpaper or photo. Toggle dark and light...` In 19.04 more space was allocated so the entire message could fit.

**Comment by mmstick** [comment]
So, either we shorten the description to fit, or we find the change in gnome-shell that's cutting the description short.
