### ISSUE TITLE
Appearance tab naming is odd

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-control-center#55]
The name of the category is "Appearance". The default tab under "Appearance" is "Background", where the secondary tab is "Appearance". I think it is kind of odd that the name of the category is not the name of the first tab, but that of the second one.

Perhaps calling the "Appearance" tab "Theme" or something of that nature and not reusing "Appearance" would be a clean solution.

![appearance](https://user-images.githubusercontent.com/7460774/66867400-71fbd200-ef58-11e9-9b75-e90d4f98a201.png)

**Comment by WatchMkr** [comment]
I don't have a good solution but we don't want to use "Theme" as that's not the function of the setting. Appearance is accurate. Light/Dark Mode is the most precise but long.

**Comment by mmstick** [comment]
Would "Dark Mode" by itself be enough of a description for it?

**Comment by WatchMkr** [comment]
I'd rather not change the name. Appearance seems the most fitting. Do we need to leave Background first so that "Change Background" when right clicked goes to the correct tab?

**Comment by mmstick** [comment]
We may be able to do that. I will see what kind of changes are necessary in gcc

**Comment by jackpot51** [comment]
We should probably just keep it as-is then
