### ISSUE TITLE
Opening Settings automatically changes theme to Pop-dark

### ISSUE THREAD

**Issue by matfantinel** [pop-os/gnome-control-center#74]
I am having this issue where, when using another dark GTK theme, opening the settings app automatically changes the GTK theme to Pop-dark. 

This does not happen when using a light theme, however.

I'm using the default Pop session and haven't fiddled much with the install, so this should be easy to reproduce. I've changed the themes using `gnome-tweak-tool` and am using Yaru-dark, for reference, but happened to other dark themes too.

**Comment by q64ceo** [comment]
+1

It seems intermittent for me, however. I can click on the devices section and have no probs with it. But when I switch to the main screen it changes automatically.

**Comment by CoreyVincent** [comment]
+1

Anytime I open Settings > Appearance it changes my theme to "pop" or "pop-dark" depending on what was selected.

Here's a video of what's happening:
[video](https://youtu.be/o8Q_69OculA)

**Comment by matfantinel** [comment]
Still happening in 20.04. This ruins the experience of using other themes.

**Comment by CoreyVincent** [comment]
@matfantinel same here, just upgraded to 20.04 and I'm having the issue still as well.

**Comment by Slotheacientone** [comment]
Having the same issues in pop!_os 20.04
