### ISSUE TITLE
20.04: Graphics info in "About" is different

### ISSUE THREAD

**Issue by leviport** [pop-os/gnome-control-center#80]
The information is not inaccurate, but it did change. It's probably from upstream, but I wanted to post it here so we could decide whether or not it was worth worrying about. We can just close this if we're fine with this change.
![1910-about](https://user-images.githubusercontent.com/13512097/76640443-8c40d880-6515-11ea-9ed2-6edb6bf0da1a.png)
![2004-about](https://user-images.githubusercontent.com/13512097/76640450-8e0a9c00-6515-11ea-8a95-df86f2757c41.png)

**Comment by jackpot51** [comment]
I think this change might come from mesa, not gnome-control-center. Check `glxinfo | grep renderer`

**Comment by leviport** [comment]
You're right, `glxinfo` is showing different output, matching what I see in the screenshots on each system. I'm thinking it's not worth worrying about, so I'll just close this issue.
