### ISSUE TITLE
Lockscreen blur preview is not working correctly

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/gnome-control-center#83]
Tested on Pop!_OS 20.04 LTS with the latest updates to GNOME and Pop Theme. WHen changing the wallpaper by right clicking on a photo from Files the lockscreen blur is not updated. It is updated if you add the photo in Settings. I can't recreate this on Arch Linux with the latest upstream GNOME.

**Comment by leviport** [comment]
I can confirm this. The lock screen does not get updated with the wallpaper if set from right clicking an image in Nautilus and selecting "Set As Wallpaper".

**Comment by jacobgkau** [comment]
I'm no longer seeing this issue today. Checked by setting the wallpaper from Files (Nautilus) by right-clicking a photo and choosing "Set As Wallpaper," then locking the screen with Super+Esc and observing that the blurred background reflects the new wallpaper. Tested with gnome-control-center 3.36.3 and 3.36.2.

@ahoneybun @leviport Can one of you confirm we can close this?

**Comment by ahoneybun** [comment]
@jacobgkau I can't recreate the issue on my end. Pop 20.04 LTS with all of the updates.

```
aaronh@pop-os:~$ apt policy gnome-control-center
gnome-control-center:
  Installed: 1:3.36.2-0ubuntu1pop1~1593712481~20.04~f932311
  Candidate: 1:3.36.2-0ubuntu1pop1~1593712481~20.04~f932311
  Version table:

```
