### ISSUE TITLE
Remove "Diagnostics" tab and disable problem reporting

### ISSUE THREAD

**Issue by brs17** [pop-os/gnome-control-center#91]
When searching for "OS Upgrade", I had typed "os" and discovered the search result for the "Diagnostics" tab in gnome-control-center. Selecting this search result shows the Diagnostics page which looks like the following:
![diagnostics](https://user-images.githubusercontent.com/7460774/80535309-cfd49200-895d-11ea-91b1-19e9a763f56d.png)

This page is not discoverable on its own in gnome-control-center. The tab also disappears if another tab is selected (for example selecting "Screen Lock").

Related, I see that the "Learn More" link goes to the System76 Privacy Policy which makes no reference to Pop!_OS.

**Comment by leviport** [comment]
On my machine I can still see Diagnostics come up in search results, but it takes me to the Screen Lock page when I try launching it.

**Comment by brs17** [comment]
> On my machine I can still see Diagnostics come up in search results, but it takes me to the Screen Lock page when I try launching it.

I have seen that happen as well. Try again with gnome-control-center open.

**Comment by leviport** [comment]
Yep, having GCC open to start with made it go to the Diagnostics page. Interesting.

**Comment by WatchMkr** [comment]
We should remove this. The language is misleading (reports don't come to us) and we don't collect data from installations anyway.
